-- Migration 0019: Replace global UNIQUE on system_barcode with partial unique index
--
-- The original UNIQUE constraint (from 0003) spans ALL rows, including soft-deleted ones.
-- This prevents barcode reuse after an item is deleted: assigning a deleted item's
-- barcode to a new item violates the constraint even though the original is gone.
--
-- Fix: drop the table-level constraint and create a partial unique index that only
-- covers live (non-deleted) rows.  Deleted items retain their barcode for restore
-- purposes, but the barcode is free for reassignment while the item stays deleted.

-- Drop the existing table-level UNIQUE constraint.
-- The constraint name is auto-generated by PostgreSQL as "items_system_barcode_key".
ALTER TABLE items DROP CONSTRAINT items_system_barcode_key;

-- Create a partial unique index on live items only.
CREATE UNIQUE INDEX idx_items_system_barcode_live
    ON items (system_barcode)
    WHERE system_barcode IS NOT NULL AND is_deleted = FALSE;
